# Generated by Django 4.2.17 on 2024-12-13 07:51

from django.db import migrations, models
import django.db.models.deletion
import trips.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, validators=[trips.validators.DestinationValidator()])),
                ('summary', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(default=1, help_text='*Duration in days is expected.')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('traveler', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='traveler.traveler')),
            ],
        ),
    ]
